FROM apache/spark:3.5.1-scala2.12-java17-python3-ubuntu

USER root

RUN pip install --no-cache-dir \
    delta-spark==3.1.0 \
    pyspark==3.5.1 \
    pandas \
    pyarrow \
    faker

COPY loader/ /opt/loader/

WORKDIR /opt/loader

CMD ["python", "load_sample_data.py"]
