FROM jupyter/pyspark-notebook:spark-3.5.0

USER root

# Install Delta Lake
RUN pip install --no-cache-dir \
    delta-spark==3.1.0 \
    grpcio \
    grpcio-status

USER jovyan

ENV SPARK_HOST=spark
ENV SPARK_PORT=15002
